
import { LogEntry, User, ThemeType } from './types';
import { TAGS, getTagById } from './constants/tags';

const STORAGE_KEY = 'space_logger_data';
const AUTH_KEY = 'space_logger_auth';
const USERS_DB_KEY = 'space_logger_users_db';
const THEME_KEY = 'space_logger_theme';

const logsKeyForUser = (userId?: string) =>
  userId ? `${STORAGE_KEY}_${userId}` : STORAGE_KEY;

export const saveLogs = (logs: LogEntry[], userId?: string) => {
  localStorage.setItem(logsKeyForUser(userId), JSON.stringify(logs));
};

export const getLogs = (userId?: string): LogEntry[] => {
  // ユーザー指定がない場合は旧仕様（共通キー）をそのまま返す
  if (!userId) {
    const legacy = localStorage.getItem(STORAGE_KEY);
    return legacy ? JSON.parse(legacy) : [];
  }

  const key = logsKeyForUser(userId);
  const userData = localStorage.getItem(key);
  if (userData) return JSON.parse(userData);

  // 旧データがあれば、現在のユーザーの領域にマイグレーションしてから返す
  const legacy = localStorage.getItem(STORAGE_KEY);
  if (legacy) {
    const parsed: LogEntry[] = JSON.parse(legacy);
    saveLogs(parsed, userId);
    localStorage.removeItem(STORAGE_KEY);
    return parsed;
  }

  return [];
};

export const saveUser = (user: User | null) => {
  if (user) {
    localStorage.setItem(AUTH_KEY, JSON.stringify(user));
    // 同時にユーザーDBも更新
    updateUserInDB(user);
  } else {
    localStorage.removeItem(AUTH_KEY);
  }
};

export const getUser = (): User | null => {
  const data = localStorage.getItem(AUTH_KEY);
  return data ? JSON.parse(data) : null;
};

// ユーザーデータベース管理
export const getUsersDB = (): User[] => {
  const data = localStorage.getItem(USERS_DB_KEY);
  return data ? JSON.parse(data) : [];
};

export const registerUser = (user: User) => {
  const db = getUsersDB();
  const exists = db.find(u => u.email === user.email);
  if (exists) return false;
  db.push(user);
  localStorage.setItem(USERS_DB_KEY, JSON.stringify(db));
  return true;
};

export const updateUserInDB = (updatedUser: User) => {
  const db = getUsersDB();
  const index = db.findIndex(u => u.id === updatedUser.id || u.email === updatedUser.email);
  if (index !== -1) {
    db[index] = { ...db[index], ...updatedUser };
    localStorage.setItem(USERS_DB_KEY, JSON.stringify(db));
  }
};

const CUSTOM_TAGS_KEY = 'space_logger_custom_tags';

// ... (existing helper functions)

// カスタムタグ管理
export const getCustomTags = (): string[] => {
  const data = localStorage.getItem(CUSTOM_TAGS_KEY);
  return data ? JSON.parse(data) : [];
};

export const addCustomTag = (tag: string) => {
  const tags = getCustomTags();
  if (!tags.includes(tag)) {
    tags.push(tag);
    localStorage.setItem(CUSTOM_TAGS_KEY, JSON.stringify(tags));
  }
};

export const removeCustomTag = (tag: string) => {
  const tags = getCustomTags();
  const newTags = tags.filter(t => t !== tag);
  localStorage.setItem(CUSTOM_TAGS_KEY, JSON.stringify(newTags));
};

// テーマ管理
export const saveTheme = (theme: ThemeType) => {
  localStorage.setItem(THEME_KEY, theme);
};


export const getTheme = (): ThemeType => {
  return (localStorage.getItem(THEME_KEY) as ThemeType) || 'dark';
};

// Initial Mock Data
export const INITIAL_LOGS: LogEntry[] = [
  {
    id: '1',
    title: 'React Hooks Deep Dive',
    duration: '2時間',
    durationMinutes: 120,
    tags: ['react'],
    memo: 'useEffectのクリーンアップ関数について深く学んだ。',
    timestamp: new Date().toISOString(),
    category: 'Frontend'
  }
];

// GitHub Synchronization
export const syncLogToGitHub = async (user: User): Promise<{ success: boolean; message?: string }> => {
  if (!user.githubUsername || !user.githubRepo || !user.githubToken) {
    return { success: false, message: 'GitHub credentials are missing.' };
  }

  const logs = getLogs(user.id);
  if (logs.length === 0) {
    return { success: true, message: 'No logs to sync.' };
  }



  // Generate Markdown
  let markdown = '# Mission Log\n\nGenerated by Space Logger\n\n| 日付 | タイトル | 学習タイプ | 学習時間 | 技術タグ | メモ |\n| --- | --- | --- | --- | --- | --- |\n';

  const getLearningTypeLabel = (type?: string) => {
    switch (type) {
      case 'input': return 'インプット';
      case 'output': return 'アウトプット';
      case 'both': return '両方';
      default: return 'その他';
    }
  };

  logs.forEach(log => {
    const date = new Date(log.timestamp).toLocaleDateString('ja-JP');
    const typeLabel = getLearningTypeLabel(log.learningType);

    // Resolve tags from IDs to Labels
    const tagLabels = log.tags.map(id => getTagById(id).label).join(', ');

    // Escape pipes in content to prevent breaking the table
    const safeTitle = log.title.replace(/\|/g, '\\|');
    const safeMemo = log.memo.replace(/\|/g, '\\|');

    markdown += `| ${date} | ${safeTitle} | ${typeLabel} | ${log.duration} | ${tagLabels} | ${safeMemo} |\n`;
  });

  const path = 'MISSION_LOG.md';
  const apiUrl = `https://api.github.com/repos/${user.githubUsername}/${user.githubRepo}/contents/${path}`;

  try {
    // 1. Check if file exists to get SHA
    let sha: string | undefined;
    const getResponse = await fetch(apiUrl, {
      method: 'GET',
      headers: {
        'Authorization': `token ${user.githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
      },
    });

    if (getResponse.ok) {
      const data = await getResponse.json();
      sha = data.sha;
    } else if (getResponse.status !== 404) {
      // Error checking file existence (excluding 404 which is fine for creation)
      const errorText = await getResponse.text();
      return { success: false, message: `Failed to check file: ${getResponse.status} ${errorText}` };
    }

    // 2. Create or Update file
    // GitHub API requires content to be base64 encoded
    // Using simple btoa for Basic Latin. For UTF-8 characters (Japanese), we need encoding trick.
    const utf8Content = unescape(encodeURIComponent(markdown));
    const contentBase64 = btoa(utf8Content);

    const putResponse = await fetch(apiUrl, {
      method: 'PUT',
      headers: {
        'Authorization': `token ${user.githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: 'Update Mission Log via Space Logger',
        content: contentBase64,
        sha: sha, // Include SHA if updating
      }),
    });

    if (putResponse.ok) {
      return { success: true };
    } else {
      const errorText = await putResponse.text();
      return { success: false, message: `Failed to sync: ${putResponse.status} ${errorText}` };
    }

  } catch (error) {
    return { success: false, message: `Network error: ${error}` };
  }
};
