
import { LogEntry, User, ThemeType } from './types';
import { getTagById } from './constants/tags';

const STORAGE_KEY = 'space_logger_data';
const AUTH_KEY = 'space_logger_auth';
const USERS_DB_KEY = 'space_logger_users_db';
const THEME_KEY = 'space_logger_theme';

const logsKeyForUser = (userId?: string) =>
  userId ? `${STORAGE_KEY}_${userId}` : STORAGE_KEY;

export const saveLogs = (logs: LogEntry[], userId?: string) => {
  localStorage.setItem(logsKeyForUser(userId), JSON.stringify(logs));
};

export const getLogs = (userId?: string): LogEntry[] => {
  // ユーザー指定がない場合は旧仕様（共通キー）をそのまま返す
  if (!userId) {
    const legacy = localStorage.getItem(STORAGE_KEY);
    return legacy ? JSON.parse(legacy) : [];
  }

  const key = logsKeyForUser(userId);
  const userData = localStorage.getItem(key);
  if (userData) return JSON.parse(userData);

  // 旧データがあれば、現在のユーザーの領域にマイグレーションしてから返す
  const legacy = localStorage.getItem(STORAGE_KEY);
  if (legacy) {
    const parsed: LogEntry[] = JSON.parse(legacy);
    saveLogs(parsed, userId);
    localStorage.removeItem(STORAGE_KEY);
    return parsed;
  }

  return [];
};

export const saveUser = (user: User | null) => {
  if (user) {
    localStorage.setItem(AUTH_KEY, JSON.stringify(user));
    // 同時にユーザーDBも更新
    updateUserInDB(user);
  } else {
    localStorage.removeItem(AUTH_KEY);
  }
};

export const getUser = (): User | null => {
  const data = localStorage.getItem(AUTH_KEY);
  return data ? JSON.parse(data) : null;
};

// ユーザーデータベース管理
export const getUsersDB = (): User[] => {
  const data = localStorage.getItem(USERS_DB_KEY);
  return data ? JSON.parse(data) : [];
};

export const registerUser = (user: User) => {
  const db = getUsersDB();
  const exists = db.find(u => u.email === user.email);
  if (exists) return false;
  db.push(user);
  localStorage.setItem(USERS_DB_KEY, JSON.stringify(db));
  return true;
};

export const updateUserInDB = (updatedUser: User) => {
  const db = getUsersDB();
  const index = db.findIndex(u => u.id === updatedUser.id || u.email === updatedUser.email);
  if (index !== -1) {
    db[index] = { ...db[index], ...updatedUser };
    localStorage.setItem(USERS_DB_KEY, JSON.stringify(db));
  }
};

const CUSTOM_TAGS_KEY = 'space_logger_custom_tags';

// ... (existing helper functions)

// カスタムタグ管理
export const getCustomTags = (): string[] => {
  const data = localStorage.getItem(CUSTOM_TAGS_KEY);
  return data ? JSON.parse(data) : [];
};

export const addCustomTag = (tag: string) => {
  const tags = getCustomTags();
  if (!tags.includes(tag)) {
    tags.push(tag);
    localStorage.setItem(CUSTOM_TAGS_KEY, JSON.stringify(tags));
  }
};

export const removeCustomTag = (tag: string) => {
  const tags = getCustomTags();
  const newTags = tags.filter(t => t !== tag);
  localStorage.setItem(CUSTOM_TAGS_KEY, JSON.stringify(newTags));
};

// テーマ管理
export const saveTheme = (theme: ThemeType) => {
  localStorage.setItem(THEME_KEY, theme);
};


export const getTheme = (): ThemeType => {
  return (localStorage.getItem(THEME_KEY) as ThemeType) || 'dark';
};

// Initial Mock Data
export const INITIAL_LOGS: LogEntry[] = [
  {
    id: '1',
    title: 'React Hooks Deep Dive',
    duration: '2時間',
    durationMinutes: 120,
    tags: ['react'],
    memo: 'useEffectのクリーンアップ関数について深く学んだ。',
    timestamp: new Date().toISOString(),
    category: 'Frontend'
  }
];

const GITHUB_API = 'https://api.github.com';
const SPACE_LOGGER_REPO = 'space-logger';
const README_PATH = 'README.md';
const README_CONTENT = `# Space Logger
このリポジトリは Space Logger で記録された学習ログを自動保存しています。
学習の継続を可視化するためのログです。
`;

export type SyncResult = {
  success: boolean;
  message: string;
  code?: 'MISSING_SCOPE' | 'REPO_NOT_FOUND' | 'OAUTH_EXPIRED' | 'ALREADY_SYNCED' | 'AUTH_ERROR';
};

const githubHeaders = (token: string) => ({
  Authorization: `Bearer ${token}`,
  Accept: 'application/vnd.github+json',
  'Content-Type': 'application/json',
});

const toBase64Utf8 = (text: string) => btoa(unescape(encodeURIComponent(text)));
const fromBase64Utf8 = (base64: string) => decodeURIComponent(escape(atob(base64)));

const getLearningTypeLabel = (type?: string) => {
  switch (type) {
    case 'input': return 'input';
    case 'output': return 'output';
    case 'both': return 'both';
    default: return 'both';
  }
};

const buildMonthlyPathFromTimestamp = (timestamp: string) => {
  const d = new Date(timestamp);
  const yyyy = `${d.getFullYear()}`;
  const mm = `${d.getMonth() + 1}`.padStart(2, '0');
  return `${yyyy}/${mm}/${yyyy}-${mm}-mission-log.md`;
};

const escapeMarkdownCell = (value: string) => value
  .replace(/\|/g, '\\|')
  .replace(/\r?\n/g, '<br>');

const buildMonthlyHeader = (timestamp: string) => {
  const d = new Date(timestamp);
  const yyyy = d.getFullYear();
  const mm = `${d.getMonth() + 1}`.padStart(2, '0');
  return `# Mission Log - ${yyyy}/${mm}
Generated by Space Logger

| 日付 | タイトル | 学習タイプ | 学習時間 | 技術タグ | メモ |
| --- | --- | --- | --- | --- | --- |
`;
};

const buildLogRow = (entry: LogEntry) => {
  const d = new Date(entry.timestamp);
  const dateLabel = `${d.getFullYear()}/${d.getMonth() + 1}/${d.getDate()}`;
  const tagLabels = entry.tags.map(id => getTagById(id).label).join(', ');
  const durationLabel = entry.duration || `${Math.max(0, Math.round(entry.durationMinutes || 0))}分`;
  return `| ${escapeMarkdownCell(dateLabel)} | ${escapeMarkdownCell(entry.title)} | ${escapeMarkdownCell(getLearningTypeLabel(entry.learningType))} | ${escapeMarkdownCell(durationLabel)} | ${escapeMarkdownCell(tagLabels || 'なし')} | ${escapeMarkdownCell(entry.memo || '')} |\n`;
};

const getGitHubLogin = async (token: string): Promise<SyncResult & { login?: string }> => {
  const response = await fetch(`${GITHUB_API}/user`, { headers: githubHeaders(token) });
  if (response.status === 401) {
    return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
  }
  if (!response.ok) {
    return { success: false, code: 'AUTH_ERROR', message: `GitHubユーザー取得に失敗しました (${response.status})` };
  }
  const data = await response.json() as { login?: string };
  if (!data.login) return { success: false, code: 'AUTH_ERROR', message: 'GitHubユーザー名を取得できませんでした。' };
  return { success: true, message: '', login: data.login };
};

const ensureSpaceLoggerRepo = async (owner: string, token: string): Promise<SyncResult> => {
  const repoUrl = `${GITHUB_API}/repos/${owner}/${SPACE_LOGGER_REPO}`;
  const repoCheck = await fetch(repoUrl, { headers: githubHeaders(token) });

  // Responsibility:
  // - OAuth scope不足とtoken失効は別のUX導線を出すため、ここでコードを厳密に分離する。
  // - repo未作成(404)はエラーではなく、作成フローに進むための正常な分岐として扱う。
  //
  // GET /repos/{owner}/space-logger
  // 200: repo exists
  // 404: repo missing (normal branch)
  // 401/403: auth issue
  if (repoCheck.ok) return { success: true, message: '' };
  if (repoCheck.status === 401 || repoCheck.status === 403) {
    return { success: false, code: 'AUTH_ERROR', message: 'GitHubリポジトリの参照権限が不足しています。' };
  }
  if (repoCheck.status !== 404) {
    return { success: false, code: 'AUTH_ERROR', message: `GitHubリポジトリ確認に失敗しました (${repoCheck.status})` };
  }

  // POST /user/repos
  // 201: created
  // 401: expired token
  // 403/404: missing scope (repo/public_repo)
  const createRepo = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST',
    headers: githubHeaders(token),
    body: JSON.stringify({
      name: SPACE_LOGGER_REPO,
      private: false,
      auto_init: true,
    }),
  });
  if (createRepo.status === 401) {
    return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
  }
  if (createRepo.status === 403 || createRepo.status === 404) {
    return { success: false, code: 'MISSING_SCOPE', message: 'GitHubに学習ログを保存するための権限がまだありません。' };
  }
  if (!createRepo.ok) {
    return { success: false, code: 'AUTH_ERROR', message: `GitHubリポジトリ作成に失敗しました (${createRepo.status})` };
  }

  const readmeUrl = `${repoUrl}/contents/${README_PATH}`;
  const readmeCheck = await fetch(readmeUrl, { headers: githubHeaders(token) });
  let sha: string | undefined;
  if (readmeCheck.ok) {
    const data = await readmeCheck.json() as { sha?: string };
    sha = data.sha;
  } else if (readmeCheck.status === 401) {
    return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
  } else if (readmeCheck.status === 403) {
    return { success: false, code: 'MISSING_SCOPE', message: 'GitHubに学習ログを保存するための権限がまだありません。' };
  } else if (readmeCheck.status !== 404) {
    return { success: false, code: 'AUTH_ERROR', message: `README確認に失敗しました (${readmeCheck.status})` };
  }

  const readmeUpsert = await fetch(readmeUrl, {
    method: 'PUT',
    headers: githubHeaders(token),
    body: JSON.stringify({
      message: 'docs: initialize Space Logger README',
      content: toBase64Utf8(README_CONTENT),
      sha,
    }),
  });
  if (readmeUpsert.status === 401) {
    return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
  }
  if (readmeUpsert.status === 403) {
    return { success: false, code: 'MISSING_SCOPE', message: 'GitHubに学習ログを保存するための権限がまだありません。' };
  }
  if (!readmeUpsert.ok) {
    return { success: false, code: 'AUTH_ERROR', message: `README更新に失敗しました (${readmeUpsert.status})` };
  }

  return { success: true, message: '' };
};

export const syncLogToGitHub = async (
  user: User,
  authToken: string | undefined,
  entry: LogEntry | null
): Promise<SyncResult> => {
  if (!authToken) return { success: false, code: 'AUTH_ERROR', message: 'GitHub OAuthトークンが見つかりません。' };
  if (!entry) return { success: false, code: 'AUTH_ERROR', message: '同期対象の学習記録がありません。' };

  try {
    const loginResult = await getGitHubLogin(authToken);
    if (!loginResult.success || !loginResult.login) return loginResult;

    const owner = loginResult.login;
    const repoResult = await ensureSpaceLoggerRepo(owner, authToken);
    if (!repoResult.success) return repoResult;

    const path = buildMonthlyPathFromTimestamp(entry.timestamp);
    const row = buildLogRow(entry);
    const fileUrl = `${GITHUB_API}/repos/${owner}/${SPACE_LOGGER_REPO}/contents/${path}`;

    let sha: string | undefined;
    let nextContent = `${buildMonthlyHeader(entry.timestamp)}${row}`;
    const currentFile = await fetch(fileUrl, { headers: githubHeaders(authToken) });
    if (currentFile.ok) {
      const current = await currentFile.json() as { sha?: string; content?: string; encoding?: string };
      sha = current.sha;
      if (current.encoding === 'base64' && typeof current.content === 'string') {
        const decoded = fromBase64Utf8(current.content.replace(/\n/g, ''));
        if (decoded.includes(row.trim())) {
          return { success: true, message: 'Already synced for this record.' };
        }
        const suffix = decoded.endsWith('\n') ? '' : '\n';
        nextContent = `${decoded}${suffix}${row}`;
      }
    } else if (currentFile.status === 401) {
      return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
    } else if (currentFile.status === 403) {
      return { success: false, code: 'MISSING_SCOPE', message: 'GitHubに学習ログを保存するための権限がまだありません。' };
    } else if (currentFile.status !== 404) {
      return { success: false, code: 'AUTH_ERROR', message: `Mission Log取得に失敗しました (${currentFile.status})` };
    }

    const putResponse = await fetch(fileUrl, {
      method: 'PUT',
      headers: githubHeaders(authToken),
      body: JSON.stringify({
        message: `feat(log): update ${path}`,
        content: toBase64Utf8(nextContent),
        sha,
      }),
    });

    if (putResponse.ok) return { success: true, message: 'GitHubに同期しました。' };

    // PUT /contents/{path}
    // 422/409: duplicated request -> idempotent success
    if (putResponse.status === 422 || putResponse.status === 409) {
      return { success: true, code: 'ALREADY_SYNCED', message: 'この記録はすでに同期済みです。' };
    }
    if (putResponse.status === 401) {
      return { success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' };
    }
    if (putResponse.status === 403) {
      return { success: false, code: 'MISSING_SCOPE', message: 'GitHubに学習ログを保存するための権限がまだありません。' };
    }
    return { success: false, code: 'AUTH_ERROR', message: `GitHub同期に失敗しました (${putResponse.status})` };
  } catch (error) {
    return { success: false, code: 'AUTH_ERROR', message: `ネットワークエラー: ${error}` };
  }
};
