import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const GITHUB_API = 'https://api.github.com'
const SPACE_LOGGER_REPO = 'space-logger'
const README_CONTENT = `# Space Logger
このリポジトリは Space Logger で記録された学習ログを自動保存しています。
学習の継続を可視化するためのログです。
`

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, content-type',
}

const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  })

const githubHeaders = (token: string) => ({
  Authorization: `Bearer ${token}`,
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
  'Content-Type': 'application/json',
})

const toBase64Utf8 = (text: string) => {
  const bytes = new TextEncoder().encode(text)
  const binary = Array.from(bytes).map(b => String.fromCharCode(b)).join('')
  return btoa(binary)
}

const fromBase64Utf8 = (base64: string) => {
  const binary = atob(base64)
  const bytes = Uint8Array.from(binary, c => c.charCodeAt(0))
  return new TextDecoder().decode(bytes)
}

const escapeCell = (v: string) => v.replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>')

interface LogEntry {
  id: string
  title: string
  duration: string
  durationMinutes?: number
  learningType?: string
  tags: string[]
  memo?: string
  timestamp: string
}

const buildMonthlyPath = (timestamp: string) => {
  const d = new Date(timestamp)
  const yyyy = `${d.getFullYear()}`
  const mm = `${d.getMonth() + 1}`.padStart(2, '0')
  return `${yyyy}/${mm}/${yyyy}-${mm}-mission-log.md`
}

const buildHeader = (timestamp: string) => {
  const d = new Date(timestamp)
  const yyyy = d.getFullYear()
  const mm = `${d.getMonth() + 1}`.padStart(2, '0')
  return `# Mission Log - ${yyyy}/${mm}\nGenerated by Space Logger\n\n| 日付 | タイトル | 学習タイプ | 学習時間 | 技術タグ | メモ |\n| --- | --- | --- | --- | --- | --- |\n`
}

const buildRow = (entry: LogEntry, tagLabels: string) => {
  const d = new Date(entry.timestamp)
  const date = `${d.getFullYear()}/${d.getMonth() + 1}/${d.getDate()}`
  const duration = entry.duration || `${Math.max(0, Math.round(entry.durationMinutes || 0))}分`
  const type = entry.learningType || 'both'
  return `| ${escapeCell(date)} | ${escapeCell(entry.title)} | ${escapeCell(type)} | ${escapeCell(duration)} | ${escapeCell(tagLabels || 'なし')} | ${escapeCell(entry.memo || '')} |\n`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders })

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) return json({ success: false, message: '認証が必要です' }, 401)

    // ANON_KEY + user JWT でクライアントを作成（RLSが適用される）
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    )

    const token = authHeader.replace('Bearer ', '')
    const { data: { user }, error } = await supabase.auth.getUser(token)
    if (error || !user) return json({ success: false, message: `認証に失敗しました: ${error?.message}` }, 401)

    // DBからGitHub tokenを取得（ブラウザには返さない）
    const { data: profile } = await supabase
      .from('profiles')
      .select('github_access_token')
      .eq('id', user.id)
      .single()

    const githubToken = profile?.github_access_token
    if (!githubToken) return json({ success: false, code: 'AUTH_ERROR', message: 'GitHub tokenが見つかりません。再連携してください。' })

    const { entry, tagLabels } = await req.json() as { entry: LogEntry; tagLabels: string }
    if (!entry) return json({ success: false, message: '記録データがありません' }, 400)

    // GitHub APIを叩く（tokenはここだけで使用）
    const userRes = await fetch(`${GITHUB_API}/user`, { headers: githubHeaders(githubToken) })
    if (userRes.status === 401) return json({ success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。再連携してください。' })
    if (!userRes.ok) return json({ success: false, code: 'AUTH_ERROR', message: `GitHubユーザー取得に失敗 (${userRes.status})` })
    const { login } = await userRes.json() as { login: string }

    const repoUrl = `${GITHUB_API}/repos/${login}/${SPACE_LOGGER_REPO}`
    const repoCheck = await fetch(repoUrl, { headers: githubHeaders(githubToken) })

    if (repoCheck.status === 404) {
      const createRepo = await fetch(`${GITHUB_API}/user/repos`, {
        method: 'POST',
        headers: githubHeaders(githubToken),
        body: JSON.stringify({ name: SPACE_LOGGER_REPO, private: false, auto_init: true }),
      })
      if (createRepo.status === 401) return json({ success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。' })
      if (createRepo.status === 403 || createRepo.status === 404) return json({ success: false, code: 'MISSING_SCOPE', message: 'GitHubに書き込む権限がありません。' })
      if (!createRepo.ok) return json({ success: false, code: 'AUTH_ERROR', message: `リポジトリ作成に失敗 (${createRepo.status})` })

      await fetch(`${repoUrl}/contents/README.md`, {
        method: 'PUT',
        headers: githubHeaders(githubToken),
        body: JSON.stringify({ message: 'docs: initialize Space Logger README', content: toBase64Utf8(README_CONTENT) }),
      })
    } else if (!repoCheck.ok) {
      return json({ success: false, code: 'AUTH_ERROR', message: `リポジトリ確認に失敗 (${repoCheck.status})` })
    }

    const path = buildMonthlyPath(entry.timestamp)
    const row = buildRow(entry, tagLabels)
    const fileUrl = `${repoUrl}/contents/${path}`

    let sha: string | undefined
    let nextContent = `${buildHeader(entry.timestamp)}${row}`

    const currentFile = await fetch(fileUrl, { headers: githubHeaders(githubToken) })
    if (currentFile.ok) {
      const current = await currentFile.json() as { sha?: string; content?: string; encoding?: string }
      sha = current.sha
      if (current.encoding === 'base64' && current.content) {
        const decoded = fromBase64Utf8(current.content.replace(/\n/g, ''))
        if (decoded.includes(row.trim())) return json({ success: true, code: 'ALREADY_SYNCED', message: 'この記録はすでに同期済みです。' })
        nextContent = `${decoded}${decoded.endsWith('\n') ? '' : '\n'}${row}`
      }
    } else if (currentFile.status === 401) {
      return json({ success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。' })
    } else if (currentFile.status === 403) {
      return json({ success: false, code: 'MISSING_SCOPE', message: 'GitHubに書き込む権限がありません。' })
    }

    const putRes = await fetch(fileUrl, {
      method: 'PUT',
      headers: githubHeaders(githubToken),
      body: JSON.stringify({
        message: `feat(log): add study log ${entry.id}`,
        content: toBase64Utf8(nextContent),
        sha,
      }),
    })

    if (putRes.ok) return json({ success: true, message: 'GitHubに同期しました。' })
    if (putRes.status === 422 || putRes.status === 409) return json({ success: true, code: 'ALREADY_SYNCED', message: 'この記録はすでに同期済みです。' })
    if (putRes.status === 401) return json({ success: false, code: 'OAUTH_EXPIRED', message: 'GitHub連携の有効期限が切れています。' })
    if (putRes.status === 403) return json({ success: false, code: 'MISSING_SCOPE', message: 'GitHubに書き込む権限がありません。' })
    return json({ success: false, code: 'AUTH_ERROR', message: `GitHub同期に失敗 (${putRes.status})` })

  } catch (error) {
    return json({ success: false, code: 'AUTH_ERROR', message: `エラー: ${error}` }, 500)
  }
})
